## Exercícios

Link para Dataset: https://www.kaggle.com/datasets/matheusfreitag/gas-prices-in-brazil

In [1]:
import pandas as pd

## Neste projeto, trabalharemos com dois arquivos csvs separados, contendo informações sobre o preço da gasolina no Brasil. 

### 1. Carregue os conjuntos de dados "gasolina_2000+.csv" e "gasolina_2010+.csv" em dois DataFrames diferentes e combine-os em um único DataFrame.

In [ ]:
df1 = pd.read_csv(r"", index_col=0)
df2 = pd.read_csv(r"", index_col=0)

df = pd.concat([df1, df2])

C:\Users\jonat\AppData\Local\Temp\ipykernel_15028\3546647542.py:2: DtypeWarning: Columns (12,14,15,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv(r"C:\\Users\\jonat\\.vscode\\python-ws\\testes\\Analisando Dados com Pandas & SQL\\projetos\\analise-precos-gasolina\\gasolina_2010+.csv", index_col=0)

### 2.Investigue as colunas e entenda o conjunto de dados usando o head() e info()

In [3]:
df.head(5)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   120823 non-null  object
 1   DATA FINAL                     120823 non-null  object
 2   REGIÃO                         120823 non-null  object
 3   ESTADO                         120823 non-null  object
 4   PRODUTO                        120823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 6   UNIDADE DE MEDIDA              120823 non-null  object
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 11  MARGEM MÉDIA REVENDA           120823 non-null  object
 12  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       120823 non-null  object
 14  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  object
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  object
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
dtypes: float64(5), int64(1), object(12)
memory usage: 17.5+ MB

### 3. Selecione a terceira entrada da coluna DATA INICIAL e verifique seu tipo.

In [5]:
type(df["DATA INICIAL"].iloc[2])

str

### 4. Você deve ter percebido que as colunas DATA INICIAL e DATA FINAL estão formatadas como string. Utilizando o método pd.to_datetime(), converta ambas colunas para Timestamp / Datetime.

In [6]:
df["DATA INICIAL"] = pd.to_datetime(df["DATA INICIAL"])
df["DATA FINAL"] = pd.to_datetime(df["DATA FINAL"])
df

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

In [7]:
type(df["DATA INICIAL"].iloc[2])

pandas._libs.tslibs.timestamps.Timestamp

### 5. Crie uma nova coluna para representar o mês e o ano (mm-aaaa), utilizando a coluna DATA FINAL como referência.

In [8]:
df["ANO-MES"] = df["DATA FINAL"].apply(lambda x: "{}".format(x.year)) + df["DATA FINAL"].apply(lambda x: "-{:02d}".format(x.month))
df

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,ANO-MES
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,2004-05
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,2004-05
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,2004-05
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,2004-05
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,2004-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05

### 6. Utilizando o value_counts(), liste todos os tipos de produtos contidos na base de dados.

In [9]:
df["PRODUTO"].value_counts()

PRODUTO
GASOLINA COMUM        23570
GLP                   23561
ETANOL HIDRATADO      23440
ÓLEO DIESEL           21194
GNV                   14469
ÓLEO DIESEL S10        9113
OLEO DIESEL S10        2376
OLEO DIESEL            2351
GASOLINA ADITIVADA      749
Name: count, dtype: int64

### 7. Filtre o DataFrame para obter apenas dados da 'GASOLINA COMUM'. Grave em uma nova variável.

In [10]:
df2 = df[df["PRODUTO"] == 'GASOLINA COMUM']

In [11]:
df2.head(5)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,ANO-MES
12064,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,GASOLINA COMUM,128,R$/l,2.029,0.007,1.99,2.070,0.318,0.003,1.711,0.02,1.651,1.7427,0.012,2004-05
12065,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,GASOLINA COMUM,395,R$/l,2.025,0.062,1.85,2.220,0.296,0.031,1.729,0.036,1.6643,1.915,0.021,2004-05
12066,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,GASOLINA COMUM,194,R$/l,2.358,0.066,2.00,2.540,0.472,0.028,1.886,0.068,1.75,2.0713,0.036,2004-05
12067,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,GASOLINA COMUM,166,R$/l,2.120,0.075,1.97,2.440,0.325,0.035,1.795,0.033,1.70701,1.9703,0.018,2004-05
12068,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,GASOLINA COMUM,106,R$/l,2.090,0.034,2.00,2.159,0.35,0.016,1.74,0.042,1.6789,1.918,0.024,2004-05

### 8. Qual o preço médio de revenda da gasolina em agosto de 2008?

In [12]:
df2[df2["ANO-MES"] == '2008-08']["PREÇO MÉDIO REVENDA"].mean()

2.6012444444444442

### 9. Qual o preço médio de revenda da gasolina em maio de 2014 em São Paulo?

In [13]:
df2[(df2["ANO-MES"] == '2008-08') & (df2["ESTADO"] == 'SAO PAULO')]["PREÇO MÉDIO REVENDA"].mean()

2.4046

### 10. Você conseguiria descobrir em qual(quais) estado(s) a gasolina ultrapassou a barreira dos R$ 5,00? E quando isso ocorreu?

In [14]:
df2[df2["PREÇO MÉDIO REVENDA"] > 5][["ESTADO", "ANO-MES", "PREÇO MÉDIO REVENDA"]].head(5)

               ESTADO  ANO-MES  PREÇO MÉDIO REVENDA
98201            ACRE  2018-05                5.053
98347            ACRE  2018-06                5.035
98493            ACRE  2018-06                5.038
98511  RIO DE JANEIRO  2018-06                5.016
98646            ACRE  2018-06                5.031

### 11. Qual a média de preço dos estados da região sul em 2012?

In [15]:
df_aux = df2[(df2["DATA FINAL"].apply(lambda x: x.year) == 2012)]
df_aux[df_aux["REGIÃO"] == "SUL"]["PREÇO MÉDIO REVENDA"].mean()

2.7214423076923073

### 12. Você conseguiria obter uma tabela contendo a variação percentual ano a ano para o estado do Rio de Janeiro?

In [18]:
df2["MES"] = df2["DATA FINAL"].apply(lambda x: x.month)
df_rio = df2[df2["ESTADO"] == "RIO DE JANEIRO"]
df_rio

C:\Users\jonat\AppData\Local\Temp\ipykernel_15028\2018772225.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["MES"] = df2["DATA FINAL"].apply(lambda x: x.month)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,ANO-MES,MES
12086,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1071,R$/l,2.045,0.109,1.700,2.599,0.254,0.053,1.791,0.047,1.6363,1.9594,0.026,2004-05,5
12113,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.040,0.113,1.700,2.599,0.252,0.055,1.788,0.049,1.5943,1.99651,0.027,2004-05,5
12140,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.042,0.108,1.700,2.599,0.252,0.053,1.79,0.046,1.63596,2.2137,0.026,2004-05,5
12167,2004-05-30,2004-06-05,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.053,0.111,1.730,2.599,0.251,0.054,1.802,0.055,1.64,2.21425,0.031,2004-06,6
12194,2004-06-06,2004-06-12,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.063,0.107,1.760,2.599,0.247,0.052,1.816,0.054,1.64,2.32425,0.03,2004-06,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120003,2021-03-28,2021-04-03,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,276,R$/l,6.102,0.197,5.599,6.559,-99999.0,0.032,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-04,4
120181,2021-04-04,2021-04-10,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,275,R$/l,6.007,0.193,5.299,6.499,-99999.0,0.032,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-04,4
120360,2021-04-11,2021-04-17,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,261,R$/l,6.016,0.209,5.399,6.516,-99999.0,0.035,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-04,4
120538,2021-04-18,2021-04-24,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,240,R$/l,6.071,0.217,5.399,6.599,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-04,4
120717,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,198,R$/l,6.099,0.208,5.480,6.599,-99999.0,0.034,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05,5

In [19]:
df_month_rio = df_rio.groupby("ANO-MES")[["PREÇO MÉDIO REVENDA", "MES"]].last()

In [20]:
(df_month_rio[df_month_rio["MES"] == 12] / df_month_rio[df_month_rio["MES"] == 12].shift(1) - 1) * 100

         PREÇO MÉDIO REVENDA  MES
ANO-MES
2004-12                  NaN  NaN
2005-12             9.233449  0.0
2006-12             0.917065  0.0
2007-12             0.355591  0.0
2008-12             0.984252  0.0
2009-12             1.637427  0.0
2010-12             2.032988  0.0
2011-12             7.105263  0.0
2012-12             0.982801  0.0
2013-12             6.777894  0.0
2014-12             4.361979  0.0
2015-12            20.461634  0.0
2016-12             3.625065  0.0
2017-12            13.643178  0.0
2018-12             5.804749  0.0
2019-12             3.802993  0.0
2020-12            -1.321321  0.0

### DESAFIO: Crie uma tabela contendo uma serie temporal com a diferença absoluta e percentual entre os valores mais baratos e caros. Apresente também ao lado os estados na qual os maiores e menores preços foram registrados.

In [26]:
df_max = df2.groupby("ANO-MES").max()["PREÇO MÉDIO REVENDA"].sort_index()
idx_max = df2.groupby('ANO-MES')["PREÇO MÉDIO REVENDA"].idxmax()

df_min = df2.groupby("ANO-MES").min()["PREÇO MÉDIO REVENDA"].sort_index()
idx_min = df2.groupby('ANO-MES')["PREÇO MÉDIO REVENDA"].idxmin()
df_diff = pd.DataFrame()

In [27]:
idx_max

ANO-MES
2004-05     12104
2004-06     12228
2004-07     12374
2004-08     12471
2004-09     12590
            ...
2021-01    118208
2021-02    119092
2021-03    119629
2021-04    120163
2021-05    120699
Name: PREÇO MÉDIO REVENDA, Length: 204, dtype: int64

In [28]:
df_diff["abs_diff"] = df_max - df_min
df_diff["perct_diff"] = (df_max - df_min) / df_min * 100
df_diff["max"] = df_max
df_diff["min"] = df_min

In [29]:
df2.loc[idx_max, :][["ESTADO", "PREÇO MÉDIO REVENDA", "ANO-MES"]]

             ESTADO  PREÇO MÉDIO REVENDA  ANO-MES
12104          ACRE                2.438  2004-05
12228   MATO GROSSO                2.496  2004-06
12374          ACRE                2.545  2004-07
12471   MATO GROSSO                2.560  2004-08
12590          ACRE                2.570  2004-09
...             ...                  ...      ...
118208         ACRE                5.213  2021-01
119092         ACRE                5.809  2021-02
119629         ACRE                6.688  2021-03
120163         ACRE                6.227  2021-04
120699         ACRE                6.258  2021-05

[204 rows x 3 columns]

In [30]:
df_diff["ESTADO_MAX"] = df2.loc[idx_max, :]["ESTADO"].values
df_diff["ESTADO_MIN"] = df2.loc[idx_min, :]["ESTADO"].values

In [31]:
df_diff["ESTADO_MAX"].value_counts()

ESTADO_MAX
ACRE              166
MATO GROSSO        25
RIO DE JANEIRO     11
RORAIMA             2
Name: count, dtype: int64

In [32]:
df_diff["ESTADO_MIN"].value_counts()

ESTADO_MIN
SAO PAULO              40
AMAPA                  38
PIAUI                  28
PARAIBA                28
PARANA                 14
AMAZONAS               14
DISTRITO FEDERAL       12
MARANHAO                9
SANTA CATARINA          6
PERNAMBUCO              4
MATO GROSSO DO SUL      3
RIO GRANDE DO NORTE     2
GOIAS                   2
CEARA                   2
BAHIA                   2
Name: count, dtype: int64